### ISSUE TITLE
Game map dimensions should be enumerated or represent units of 25

### ISSUE THREAD

**Issue by mickeelm** [cygni/snakebot#21]
Given the decision that a map dimension only can be a multiple of 25, this should be more obviously reflected in the client code. E.g. instead of integer-input, enumerate like for example:

small(25)
medium(50)
large(75)
x-large(100)

If we don't want to limit ourselves like this (e.g. it should be possible to have a 475x650 board) another option is to work with size units (integers). 1x1 would be like 25x25 works now, 4x4 would make it 100x100, 2x5 is 50x125 etc...

**Comment by blackenedsystems** [comment]
For clarity ... the world doesn't need to be a square, we can combine sizes so that the world is SMALLxMEDIUM, etc
