### ISSUE TITLE
Implement ping/pong to keep clients alive

### ISSUE THREAD

**Issue by emilb** [cygni/snakebot#37]
Let all clients send a ping over the websocket every 30 secs. The server replies with a pong and thus keeping the socket alive.

**Comment by blackenedsystems** [comment]
Implemented heartbeat logic.  Couldn't see how to have a single heartbeat - the player connections and the FXClient use different mechanisms, so there's a player heartbeat and api heartbeat.  Maybe there's a cleaner way to do this?

**Comment by emilb** [comment]
Took some of Allans work but changed it to HeartBeatRequest.
