### ISSUE TITLE
Implement ClientInfo message

### ISSUE THREAD

**Issue by emilb** [cygni/snakebot#38]
For statistics it is interesting to know what language, operating system etc a client is using. This is especially good to know the days before a student och client event so we can prepare guides and the correct responsiveness to questions.

I suggest we let clients, at any time, send a ClientInfo message over the WebSocket. This would only be needed once per session and could come at any time but perhaps a good time would be just before a "RegisterForPlay" message.
```
ClientInfo {
   programingLanguage: "JavaScript",
   OS: "Linux",
   IP: "xxx.xxx.xxx.xxx",
   baseClientVersion: "0.0.8"
}
```

**Comment by blackenedsystems** [comment]
Actual JSON is:

ClientInfo {
   language: "JavaScript",
   operatingSystem: "Linux",
   ipAddress: "xxx.xxx.xxx.xxx",
   clientVersion: "0.0.8"
}
